In [3]:
import numpy as np
F1 = np.array([[1,2],[3,4]]) # 2x2
F2 = np.array([[2,2],[2,2]]) # 2x2

print(F1)
print(F2)
print()

print( F1 + F2 ) # 요소끼리의 덧셈

print()
print( F1 * F2 )  #요소끼리의 곱셈

print()
print( F1 @ F2 ) # a@a 내적 = 행렬곱은 이것으로 함

# 1,2   @  2,2   => 6,6
# 3,4      2,2     14,14    # 두 벡터의 사이각을 구해 차원 확장

# 딥러닝 -> 한번에 여러개의 변수에서 2개로 축소시키는게 아니라 
#           조금씩 차원 축소( 차원축소는 즉 행렬곱: 내적 ) 해서 값을 얻어간다.

[[1 2]
 [3 4]]
[[2 2]
 [2 2]]

[[3 4]
 [5 6]]

[[2 4]
 [6 8]]

[[ 6  6]
 [14 14]]


# 행렬은 나눗셈이 없어서 역행렬 곱해야 한다

# 역행렬  정의

###       A       x       = b
### (n x n ) (n x 1) = n x 1

# A 는  행렬(매트릭스) 



#  A^-1A=I가 되는 행렬

####    항등원인 숫자 1처럼 곱했을 때 

# AI=A, IA=A와 같이 자기자신이 되게 하는 행렬



#    역행렬=> I를 identity matrix
        
#   Ax = b → 양쪽에 역행렬 곱하면

#                                    ( A^-1Ax = A^-1b ) 

#                                 → ( I* x = A^-1b )→ x = A^-1b


In [4]:
# 방정식 해 (x구하기)
A = np.array([[2,1,-2],[3,0,1],[1,1,-1]])
print(A)

print()
b = np.transpose(np.array([[-3,5,-2]]))  #열로 전치
print(b)

# A x = b
# x 벡터를 구해라 

[[ 2  1 -2]
 [ 3  0  1]
 [ 1  1 -1]]

[[-3]
 [ 5]
 [-2]]


# A x = b

# x 벡터를 구해라 

In [ ]:
# 방정식의 해


#        A 행렬 (3x3)     x    x라는 벡터(열벡터)                 =   b (열벡터) b값을 구해라
#  A의 행렬의 1열 수  (2) x (x1,1) +  (1) x (x,1,2) +  (-2) x (x,1,3) =    -3
#  A의 행렬의 2열 수  (3) x (x1,1) +  (0) x (x1,2)  +  ( 2) x (x1,3)  =    5
#  A의 행렬의 3열 수  (-1) x (x1,1) + (1) x (x1,2)  +  (-1) x (X1,3)  =   -2


# x 열벡터를 구하기 =>  Ax = b    => x = A^-1 * b

In [5]:

x = np.linalg.solve(A,b)  #A 의 역행렬을 구해서 b와 곱해줌
print(x)

[[ 1.]
 [-1.]
 [ 2.]]


In [6]:
np.linalg.inv(A) # A의 역행렬 구하기 # 행렬 계산기로 A 의 역함수를 구하면 이값이 나옴

array([[ 0.25,  0.25, -0.25],
       [-1.  ,  0.  ,  2.  ],
       [-0.75,  0.25,  0.75]])

In [7]:
np.dot(np.linalg.inv(A),b)   #A의 역행렬에 b 곱해주면  행렬곱

array([[ 1.],
       [-1.],
       [ 2.]])

In [8]:
np.linalg.inv(A)@b   # 내적 @ 행렬에서는 곱셈이 내적이므로 => * 일반 곱셈은 그냥 요소끼리 곱셈

array([[ 1.],
       [-1.],
       [ 2.]])

# np.dot() 행렬곱 함수

# np.linalg.inv(A)  # 역행렬 함수

In [ ]:
Python NumPy의 삼각함수는 radian을 사용하기 때문에 degree 를 radian으로 바꿔주기 위해서
각도를 넣어서 계산시 degree * np.py/180 을 해줌
        
    np.sin(np.array((0., 30., 45., 60., 90.))*np.pi / 180.)

    Out[2]: array([ 0 ,  0.5 ,  0.70710678,  0.8660254 ,  1.  ])

    
    np.cos(np.array((0., 30., 45., 60., 90.))*np.pi / 180.)


    Out[3]: array([  1.00000000e+00,   8.66025404e-01,   7.07106781e-01,
                 5.00000000e-01,   6.12323400e-17])



출처: https://rfriend.tistory.com/296 [R, Python 분석과 프로그래밍의 친구 (by R Friend)]
        

In [31]:
a = np.array([0,1,0])   # y
print(a)
a1 = np.array([0,1,0])
print(a1)
b = np.array([1,0,0])   # x
print(b)
print()

print(np.linalg.norm(a)) # 벡터의 크기 np.linalg.norm()
print(np.linalg.norm(b))
print()


# 내적 = > 행렬곱 np.dot()
res = np.dot(a,b)  # 내적 사이각 = 직각
print("cos90도는 :" ,res)
# |a||b| cos90
#  1*1  * 0

res1 = np.dot(a,a1)  # 내적 사이각 = 직각
print("cos0도는 :" ,res1)

[0 1 0]
[0 1 0]
[1 0 0]

1.0
1.0

cos90도는 : 0
cos0도는 : 1


In [29]:
c = np.array([1,1,0])             # cos 45도
print(c);print(np.linalg.norm(c))  #



#cos90 = 0 
rad = res / (np.linalg.norm(a))*(np.linalg.norm(b))   # cos(theta)
rad # 내적 값을 a 벡터크기와 b 벡터크기의 곱으로 나눠주면 theta = 내적사이값 나옴 = cos90

[1 1 0]
1.4142135623730951


0.0

cos(theta)

# 두 벡터의 행렬곱 / 각 벡터의 크기 * 각 벡터의 크기

In [32]:
print("cos90도 theta" , rad) # 내적사이각이 직각이라서 cos90 = 0 이라 내적은 = 0
print()
print(" cos@ 의 역삼각함수 구하는 arccos() ")
print(np.arccos(rad))# theta 값을 구함

print()
print("사람이 알아보는 각도로 표현")
print(np.degrees(np.arccos(rad)))  


# arcsin, arctan 등 다 가능. 우리는 cos@ 만 쓰니가 = > theta

cos90도 theta 0.0

 cos@ 의 역삼각함수 구하는 arccos() 
1.5707963267948966

사람이 알아보는 각도로 표현
90.0


# 정방향행렬 (2x2) 행/렬 같은 * 역행렬 = identity( 단위행렬 )

In [36]:
x = np.array([[1,2], [3,4]])
print(x)
print()

y = np.linalg.inv(x) # 역행렬함수 이용
print(y)


np.dot(x,y) # 행렬곱 = x 와 x의 역행렬 x^-1 둘을 곱하면 => 단위행렬 답이 나옴 (1 0)
            #                                                                 (0 1)

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [48]:
# 다음 방정식의 해를 구하고 검산하시오

x + y + z = 6
   2y + 5z = -4
2x + 5y -z = 27

IndentationError: unexpected indent (<ipython-input-48-3d47f4fb96a9>, line 4)

In [41]:
c = np.array([[1, 1 ,1],[0, 2, 5],[2, 5, -1]])
print(c)

print()
d = np.transpose(np.array([[6,-4, 27]]))

# c * x = d 일때
x = np.linalg.solve(c,d) # x는 역행렬 
print(x)

print() # 다른 2가지 방법으로도 답
#역행렬 곱해주면 계산되니까
print(np.dot(np.linalg.inv(c),d))
np.linalg.inv(c)@d

[[ 1  1  1]
 [ 0  2  5]
 [ 2  5 -1]]

[[ 5.]
 [ 3.]
 [-2.]]

[[ 5.]
 [ 3.]
 [-2.]]


array([[ 5.],
       [ 3.],
       [-2.]])