# Numpy

In [9]:
# flask
# import flask # 웹서버를 연결시켜주는 기능 5000번 포트로 서비스


https://pinkwink.kr/715 기본 이론은 홈페이지에서 볼것.

In [5]:
import numpy as np  #별칭, class로 구성 -> numpy 불러와서 np로 쓰겠다.

print(np.__version__)  #상위 오브젝트가 가진 속성

1.16.5


In [71]:
def pprint(arr):        #ndarray : numpy의 기본 데이터 배열
    print("type:{}".format(type(arr)))
    print("shape:{}, dimension:{}, dtype:{}".format(arr.shape, arr.ndim, arr.dtype))
    print("Array's Data:\n", arr)
    # 숫자의 디폴트는 int32

a = np.array([1,2,3]) #ndarray 생성함수 : 매개변수 : 리스트
pprint(a) ;print()

a = np.array([[1,2,3],[4,5,6]]) #ndarray 생성함수 : 매개변수 : 리스트
pprint(a) 

type:<class 'numpy.ndarray'>
shape:(3,), dimension:1, dtype:int32
Array's Data:
 [1 2 3]

type:<class 'numpy.ndarray'>
shape:(2, 3), dimension:2, dtype:int32
Array's Data:
 [[1 2 3]
 [4 5 6]]


In [74]:
arr =[1.0,2.0,2.0] #리스트 하고 배열의 차이를 볼것. ndarray는 소수점 .으로만 표기
print(arr)
print(type(arr));print()

arr = np.array([1.0,2.0,2.0])
print(arr)
type(arr)


[1.0, 2.0, 2.0]
<class 'list'>

[1. 2. 2.]


numpy.ndarray

# np.array( ) 
#ndarray 생성함수 => 매개변수는 자료형 여러가지 가능

In [166]:
# 인스턴스 상태
a = np.array([0,1,2,3,4,5,6,7,8,9])  #ndarray
print(id(a)) # python core 주소값 확인
print(a.size) #데이터 개수
print(a.astype(np.float32)) #데이터 타입변경, 리스트에 int 형태에서 float로 변경할때
# 위에서 dtype: int32라고 나왔는데 np.float32 로 적어서 자료형 변경 가능.
print(a.dtype) # <= 숫자형
# numpy는 행중심, 동질적 

a

2193525566400
10
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
int32


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
print(a.dtype.itemsize) # 각 1개의 데이터는 4 바이트
print(a.dtype.itemsize*a.size) #a.size 는 데이터개수로 10개 => 전체 메모리 사이즈 40 바이트
#iterator for in range => list


4
40


## np.arange(숫자) 0부터 그 숫자-1까지 (파이썬에서 마지막수 포함안함)

In [15]:
a = np.arange(1000) #0 부터 1000까지 ndarray 리스트로 만들어짐 
print(a.size); print(a.dtype)
a

1000
int32


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

# ndarray 초기화 함수들

In [ ]:
# 1로 채워진 정해진 크기의 행렬을 만드는 ones
# 0으로 채워지는 zeros
# 단위행렬 만드는 eye

In [16]:
print(np.zeros((3,4))) # 0 // 튜플로 3행 4열 표기, default
zero = np.zeros((3,4))
print(zero.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [17]:
print(np.zeros([3,4]))
zero2 =np.zeros([3,4])
print(zero2.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
float64


In [18]:
print(np.ones((2,3,4), dtype=np.int16)) #1 숫자를 영어로 써주면 // 3차원으로 1면*2층, 3행 4열 
#int32 가 아니라 int16 으로 저장
a = np.ones((2,3,4))
print(a.dtype) 
print(a.size) # 데이터 24개
print(a.dtype.itemsize) #데이터 1개 => 8바이트
a

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
float64
24
8


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
print(np.full((2,2),7)) # 2행 2열로 만드는 ndarray 에 7로 채워라
a

[[7 7]
 [7 7]]


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

# np.eye() 단위행렬 만드는 함수

In [20]:
print(np.eye(4)) #대각행렬 identity  행렬연산에서 항등원으로 쓰이는 대각선 1. 
eye = np.eye(4)
print(eye.dtype)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
float64


In [21]:
print(np.empty((4,2))) # 4행 2열로 

[[0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.30427764e-321]
 [7.56592337e-307 9.34588060e-307]]


# ndarray 에서는 range 표기를 a+range

In [161]:
a = np.arange(0,100,10) # ndarray 에서는 range 표기를 a+range
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
indices=[1,5,-1]
print(indices)
b = a[indices]
print(b) # 인덱스 위치로 사용 => 1,5 ,-1 인덱스위치의 값만 호출
#내가 원하는 값을 호출할때 R에서도 [] 호출

[1, 5, -1]
[10 50 90]


In [162]:
an =np.arange(11,35) # arange 로 range 수를 넣어서 ndarray 를 만들면 1차원으로 생성됨
print(an)

an.shape =(5,5) # shape 으로 5행 5열 지정  => 데이터 갯수가 5행5열에 맞아야만 shape 지정됨
print(an)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34]


ValueError: cannot reshape array of size 24 into shape (5,5)

In [28]:
an =np.arange(11,36) # arange 로 range 수를 넣어서 ndarray 를 만들면 1차원으로 생성됨
print(an)

an.shape =(5,5) # shape 으로 5행 5열 지정  => 데이터 갯수가 5행5열에 맞아야만 shape 지정됨
print(an)

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35]
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [29]:
print(type(an))
print(an.dtype)
print(an.size) # 데이터갯수 25
print(an.dtype.itemsize) #int32 숫자 한개는 4바이트
print(an.shape) #몇행 몇열인지 확인
print(an.ndim) # 2차원
print(an.nbytes) # 총 100 바이트
print(an.dtype.itemsize*an.size) # 25개수 * 한개당 4바이트 = 총 100 qkdlxm

print()
print(an.strides)# 5행 5열 => 다음행의 데이터는 몇바이트를 건너 뛰는가 # 다음 열은 몇바이트 건너뛰는가

<class 'numpy.ndarray'>
int32
25
4
(5, 5)
2
100
100

(20, 4)


In [30]:
arr = np.arange(10)
print(arr)
print(type(arr))
print(arr[5]) # 0~ 5 까지니까 6번째 인덱스 호출
print(arr[5:8]) # 마지막 인덱스는 불포함 => 파이썬은 마지막 수 불포함!! 잊지 말것
arr[5:8] =12 # 인덱스 위치에 date 변경 update
print(arr)
print(arr[1:6])

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
5
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[ 1  2  3  4 12]


In [167]:
arr3= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr3) #3행 3열로 넣고 싶을때 [] 리스트로 묶어서 1행씩 지정
print(arr3.shape)

arr4= np.array([[1,2],[1,3],[1,4],[1,5]]) # 4행만들기, 
arr4

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


array([[1, 2],
       [1, 3],
       [1, 4],
       [1, 5]])

In [32]:
print(arr3[0]) #0 첫번째 인덱스 호출하면 1개의 행이 나옴
print(arr3[0][2]) #0 첫번째 인덱스 안에 2 => 3번째 값 호출


[1 2 3]
3


In [33]:
print(arr3[,2]) # 첨자 생략 불가함

SyntaxError: invalid syntax (<ipython-input-33-c5dc7263b542>, line 1)

In [34]:
print(arr3[0,2]) #[0][2] 와 똑같음 [0 첫번째 행의 3번째 데이터 값 호출]
print(arr3[0][2])

3
3


In [35]:
print(arr3[:2]) # 0,1 = 2번째행까지
print(arr3[:2,1:])# 2번째 행까지 2번째 data 부터 끝까지
print(arr3[:,1:]) #처음부터 끝행까지 다 불러와서 2번째 data에서 끝까지
print(arr3[1,:2]) #1 : 2번째 행 호출 => 0,1  데이터까지
print(arr3[2,:1]) #2 : 3번째 행 호출 => 0  데이터 호출

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]]
[[2 3]
 [5 6]
 [8 9]]
[4 5]
[7]


In [36]:
arr3[:2,:1]=0
arr3 #자리를 지정해서 data 치환

array([[0, 2, 3],
       [0, 5, 6],
       [7, 8, 9]])

In [37]:
arr3[2,2]=1 #3번째 행의 3번째 data 값을 1로 바꿔라 
arr3

array([[0, 2, 3],
       [0, 5, 6],
       [7, 8, 1]])

# 실제 저장은 일렬로, 사람이 데이터를 다루는 것은 입체로
#실제로 저장은 일렬로 쭉 이어서 저장이 되는것 / 사람이 보는것은 입체로 보는것 

### 행렬연산에서 앞의 행렬열수와 뒤의 행렬의 행수를 일치 시켜야만 행렬곱이 가능하다
#행렬곱에서 행렬의 앞뒤를 바꾸면 안됨

In [38]:
print( "strides의 값", np.ones((3,4,5),dtype=np.float64).strides )
#다음 면으로 넘어가려면 160바이트 필요 => 1면당 160바이트 사용 (4행 * 40 바이트 )
#다음 행으로 넘어가려면 40 바이트 필요 => 1행당 40바이트 먹음 (각 8바이트 씩이니 5열)
#다음 열 = 즉 한개의 데이터는 8byte

strides의 값 (160, 40, 8)


# 문제 

In [39]:
arr3d = np.array([ [[1,2,3],[4,5,6]],[[6,5,4],[3,2,1]]]) #2면 으로 만들고 싶을때 
print("첫면은\n",arr3d[0])
print("첫차원 첫행은",arr3d[0,0])
print("동일한 표기는", arr3d[0][0])
print("첫 요소는 =",arr3d[0,0,0])
print()
print(" 문제: 2면에서 5를 출력하라")
arr3d


첫면은
 [[1 2 3]
 [4 5 6]]
첫차원 첫행은 [1 2 3]
동일한 표기는 [1 2 3]
첫 요소는 = 1

 문제: 2면에서 5를 출력하라


array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [40]:
print("답:", arr3d[1,0,1])
print(" 2면에서 끝행끝열의 수는 ? :",arr3d[1,1,2])

답: 5
 2면에서 끝행끝열의 수는 ? : 1


In [41]:
arr4= np.array([[[1,2],[1,3],[1,4],[1,5]],[[1,2],[1,3],[1,4],[1,5]]] ) 
arr4

array([[[1, 2],
        [1, 3],
        [1, 4],
        [1, 5]],

       [[1, 2],
        [1, 3],
        [1, 4],
        [1, 5]]])

# 백업이 안됨

###                             old_values=arr3d  대입 : 주소를 복사해옴

In [42]:
old_values=arr3d.copy() # copy() 함수를 이용하면 arr3d 오프젝트 카피
old_values

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [43]:
old_values2=arr3d
old_values2

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [44]:
arr3d[0]=42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [45]:
old_values2 # arr3d의 주소값을 가져오기때문에 백업이 안됨

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [46]:
old_values # 치환하기 전에 copy 한것이기때문에 다른 object가 됨

array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [47]:
print("이전값으로 복구")
arr3d=old_values # 값을 모두 치환가능 !  같은차원 같은행 같은 열이기에 
arr3d

이전값으로 복구


array([[[1, 2, 3],
        [4, 5, 6]],

       [[6, 5, 4],
        [3, 2, 1]]])

In [48]:
Z=np.arange(36)
print(Z)
Z = Z.reshape((6,6))
print(Z)
print()
reshape2=Z.reshape(2,3,6)
print(reshape2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]]

 [[18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [49]:
arr=np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


# 데이터 행 내 숫자 섞기 

# reshape() 함수 이용해서 arange() 로 만들어준 ndarray 

# 일렬 데이터 저장 => 행렬 만듦

In [50]:
print(arr[[1,5,7,2]]) # 1인덱스 :2번째 행,/ 5인덱스 :6번째 행 / 7인덱스 : 8번째행

print(arr[1]) # 2번째 행 출력
print(arr[1,1]) #2번째행의 2번째열 출력

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]]
[4 5 6 7]
5


In [51]:
print( arr[[-1,-5,-7,-2]]) 
print()
print( arr[[1,5,7,2], [0,3,1,2]] )
# 2번째 행의 0인덱스 / 6번째행의 3인덱스:4번째수 / 
# 8번째행의 2번째수 / 3번째행의 3번째수
# arr[ [행]  ,  [렬] ]  => 데이터만 불러서 출력

[[28 29 30 31]
 [12 13 14 15]
 [ 4  5  6  7]
 [24 25 26 27]]

[ 4 23 29 10]


In [170]:
arr3[[0,2,1]]    #array로 만들어준 함수도 역시 순서뒤섞기 가능

array([[1, 2, 3],
       [7, 8, 9],
       [4, 5, 6]])

# fancy 인덱싱 = 먼저 행을 지정해줘야한다

위와 다르게 컴마 없기 때문에  데이터만 불러서 행출력해준뒤 [: 모든열 다불러라, [원하는 순서로] ]

In [52]:
print(arr[[1,2,5,7]][:,[0,1,2,3]])

[[ 4  5  6  7]
 [ 8  9 10 11]
 [20 21 22 23]
 [28 29 30 31]]


In [53]:
print(arr[[1,5,7,2]][:,[0,3,1,2]])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


# 0 ~ 55 까지 6X6 array 만들기 (이중 for 문)

In [57]:
arr=[]
for i in range(6):
    ad=[]
    for j in range(6):
        ad.append(i*10 + j)
    arr.append(ad)
print(arr)

[[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25], [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51, 52, 53, 54, 55]]


# tile()함수 => 데이터 반복해서 행렬 만들때 사용

In [186]:
v=np.array([1,0,1]) #ndarray 로 만들어줌
print("ndarry",v);print(v.dtype)
print(v.astype(np.int16))
print(v.astype(np.float32))
print()

# 타일 출력하기
vv=np.tile(v,(4))#4번 반복
print(vv);print(vv.shape)


print("np.tile() 함수에 v 를 넣으니 4번반복 12열로 출력됨");print()
# 12열 표기할때 (,12) 가 아니라 (12,) 특이함

vv=np.tile(v,(4,1))#4번 반복 = > 반복할때마다 [] 리스트 상태로
print(vv);print(vv.shape)

ndarry [1 0 1]
int32
[1 0 1]
[1. 0. 1.]

[1 0 1 1 0 1 1 0 1 1 0 1]
(12,)
np.tile() 함수에 v 를 넣으니 4번반복 12열로 출력됨

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
(4, 3)


# 산술연산 : 더하기

In [191]:
x=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]]) #4행 3열 만듦
print(x);print()

print("산술연산 가능")
y = x +vv
print(y)
# 배열 내에 요소끼리 연산되서 결과값나옴 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

산술연산 가능
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


# 더하기 연산에서 굳이 행이 (같은 수) 일필요는 없음

In [192]:
print(v)
x+v #4행3열과 1행3열의 연산이 가능
    # => 모든행에 계속 반복됨, 첫행만 더해지는게 아니라

[1 0 1]


array([[ 2,  2,  4],
       [ 5,  5,  7],
       [ 8,  8, 10],
       [11, 11, 13]])

In [193]:
print(x)
print();print(vv)
y = x + vv
print("=")
print(y) # 위의 연산값( x + V ) 와 아래 결과값이 동일하다 ㅎㅎㅎ 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
=
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [195]:
y =x + 3 # 상수는 모든데이터에 일치해서 각 데이터마다 +3 더해진다.
y

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [197]:
y - 1 # 뺄셈 가능

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [198]:
y / 2 # 나눗셈 가능

array([[2. , 2.5, 3. ],
       [3.5, 4. , 4.5],
       [5. , 5.5, 6. ],
       [6.5, 7. , 7.5]])

# 거듭제곱(행열 곱) : @ = > 너는 내적

In [94]:
x = np.arange(6).reshape((3,2))
print(x)


x@x

[[0 1]
 [2 3]
 [4 5]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

In [100]:
x@x => 에러 : 앞의 행렬 열수와 뒤의 행렬의 행수가 일치하지 않아서 에러
    # (3x2)(3x2) : 앞의 행렬 열수와 뒤의 행렬의 행수가 일치하지않아서 에러가 난다
    #행렬의 곱셈은 ( m x k ) @ ( k x n ) = ( m x n ) 이 되는 것
    
    위의 연산을 하려면 x 를 전치행렬시켜줘야함 => (2 x 3) 으로 

SyntaxError: invalid syntax (<ipython-input-100-87a9c3c493e3>, line 1)

In [101]:
print(np.transpose(x)) # 전치행렬(T)  => [ [0,2,4] [1,3,5]] 2행 3열로 바뀜

[[0 2 4]
 [1 3 5]]


In [99]:
x@x.T

# 0X0 + 1x1 , 0x2 + 1x3 , 0x4 + 1x5
# 2x0 + 3x1 , 2x2 + 3x3 , 2x4 + 3x5
# 4x0 + 5x1 , 4x2 + 5x3 , 4x4 + 5x5

array([[ 1,  3,  5],
       [ 3, 13, 23],
       [ 5, 23, 41]])

# 이건 진짜 잘 모르겠음.......

# trnaspose ( 전치) 행과 열 바꾸기



In [7]:
arr=np.arange(24).reshape((2,3,4)) #2면 3행 4열
print(arr);print()

#면 행 바꾸기
print( "면 / 행 ")
print(arr.transpose(1,0,2)) #reshape 함수의 인덱스 위치를 바꾸게 함 # 3면 2행 4열
#   (2,3,4) => (3,2 = 1,0 위치 바꾸기????)


print();print("행 / ")
print(arr.transpose(0,2,1)) # 2면은 그대로 4행 3열
#       (2,3,4)=> (0,4,3  = 2와 1 위치 바꾸기)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

면 / 행 
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]

행 / 
[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]


# 색인 처리
https://pinkwink.kr/716?category=522424

# Boolean indexting(True/False)

In [111]:
name = np.array(['Seoul','Daejun','chungju',
                 'seoul','chungju', 'Daejun', 'Daejun'])
name

array(['Seoul', 'Daejun', 'chungju', 'seoul', 'chungju', 'Daejun',
       'Daejun'], dtype='<U7')

In [115]:
print(name=='Seoul') # 논리형타입으로 서울이 들어있는 위치만 True

[ True False False False False False False]


In [112]:
data=np.random.randn(7,4) #랜덤으로 숫자를 넣어서 7행 4열 만듦
data

array([[ 0.50232254, -0.97863822, -1.429228  , -0.47486218],
       [-0.22763273,  0.92798347,  0.14602563,  1.47884558],
       [ 0.21297699,  0.41709344,  1.49194755, -0.09402923],
       [ 1.40229558, -0.0922478 ,  1.57350794, -0.19400756],
       [ 0.02019306,  0.49661621,  1.00745798, -1.0190007 ],
       [-0.49271137,  0.03586275,  2.22822121,  0.73183487],
       [-1.32814438,  0.28434916,  1.83434026, -0.68577592]])

In [116]:
print(data[name=='Seoul'])
# 첫번째있는 0번행만 출력, true 인 경우가 0인덱스라서

[[ 0.50232254 -0.97863822 -1.429228   -0.47486218]]


In [117]:
print(data[name=='Daejun']) # 대전은 1번 5번,6번행 => 2번째 6번째 7번째

[[-0.22763273  0.92798347  0.14602563  1.47884558]
 [-0.49271137  0.03586275  2.22822121  0.73183487]
 [-1.32814438  0.28434916  1.83434026 -0.68577592]]


In [118]:
print(data[name=='Seoul',2:]) 
#0번행 출력, 그중에서 2인덱스열부터 끝까지=> 3열,4열

[[-1.429228   -0.47486218]]


In [119]:
print(data[name=='Seoul',3])

[-0.47486218]


In [121]:
print(name!='Seoul')

[False  True  True  True  True  True  True]


In [122]:
print(~(name=='Seoul'))

[False  True  True  True  True  True  True]


 # 논리형에서 ~() => ! 와 같음

In [132]:
mask = (name == 'Seoul') | (name=='chungju') 
print(mask)


[ True False  True False  True False False]


In [133]:
print(data[mask])

[[ 0.50232254 -0.97863822 -1.429228   -0.47486218]
 [ 0.21297699  0.41709344  1.49194755 -0.09402923]
 [ 0.02019306  0.49661621  1.00745798 -1.0190007 ]]


In [136]:
data=np.random.randn(7,4) #랜덤으로 숫자를 넣어서 7행 4열 만듦
data
# 할때마다 수 바뀜 =randn 함수는 그러함 / seed 고정 해주면 계속 똑같은 수

array([[ 1.83406133,  1.32712521,  2.45204737, -1.22826428],
       [-0.20016391, -2.4256985 ,  0.060955  , -0.4652452 ],
       [-0.21272975, -0.06978404,  0.77831254, -0.59324607],
       [ 1.29757822,  0.33227693,  0.43637443,  0.38927042],
       [-0.39960612,  0.1123511 ,  0.86637669,  0.70016293],
       [ 1.07103974,  0.1448714 ,  0.4633243 ,  0.56385827],
       [ 0.69126444,  0.26345264, -0.13406747,  1.15861687]])

# Zip 으로 데이터 각각 요소별 묶기

In [137]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
print(xarr);print()


yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
print(yarr);print()


cond = np.array([True, False, True, False, True])
cond

[1.1 1.2 1.3 1.4 1.5]

[2.1 2.2 2.3 2.4 2.5]



array([ True, False,  True, False,  True])

In [202]:
print(zip(xarr, yarr, cond))   
# zip : 요소별로 데이터 묶음, zip은 고유포멧이라서 안보이고
print()
                              # 그래서 list해서 보내줘야한다


print(list(zip(xarr, yarr, cond)))  

# 결과값 보면 1행 1열끼리, 2행 2열끼리 , 3행 3열끼리 계속 묶임               


[(1.1, 2.1, True), (1.2, 2.2, False), (1.3, 2.3, True), (1.4, 2.4, False), (1.5, 2.5, True)]


In [203]:
print()
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]   
# 3항 연산자
print("result = ",result)



result =  [1.1, 2.2, 1.3, 2.4, 1.5]


In [142]:
#True 일때는 xarr 에서 불러오고 False 일때는 yarr  => 결국 위에 조건문과 동일

re = np.where(cond, xarr, yarr) 
re

array([1.1, 2.2, 1.3, 2.4, 1.5])

# np.where() 함수 => 조건문

In [144]:
# random 난수 정규분포에서 출력 16개 출력
arr = np.random.randn(4,4)
print(arr)
print()


print(np.where(arr > 0, 2, -2)) 
#arr > 0 조건에 맞으면 2 / false 이면 -2 로 데이터를 치환해라

[[-0.24837558 -1.50931431 -0.41428583  0.69108385]
 [ 0.58052913 -0.1810566  -0.15339259 -0.05868219]
 [-1.16481083 -0.16783616 -0.66633258  0.16576002]
 [-1.34573899 -0.93412892  2.38604338  0.91145222]]

[[-2 -2 -2  2]
 [ 2 -2 -2 -2]
 [-2 -2 -2  2]
 [-2 -2  2  2]]


# zeros_like

In [147]:

x = np.arange(1,10001)
y = np.arange(10001,20001)

z = np.zeros_like(x)   # zeros_like : 다른 행렬과 같은 사이즈로 초기화  / ..?
for i in range(10000):
    z[i] = x[i] + y[i]

z

array([10002, 10004, 10006, ..., 29996, 29998, 30000])

# np.exp : 지수함수e

# y = a^x

###        에서 y 값을 모를때 지수함수 e

In [151]:
a = np.array([1,2,3,4])
b = np.array([4,2,2,4])
print("a=b 조건에서")
print("all = 전부같을때;",np.all(a == b))  # all : 전체가 참일때 참
print("any = 하나라도 같은것이 있으면",np.any(a == b))  # any : 하나라도 참이면 참


a=b 조건에서
all = 전부같을때; False
any = 하나라도 같은것이 있으면 True
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [152]:
print(np.exp(a))    # 지수함수 (자연대수 : 2.718)



[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [ ]:

ndarray
CPU에서 감당이 안되는걸 GPU로 행렬형태로 던져서 속도 빠르게. 
한꺼번에 대량을 계산한다(천단위) 행열이 하는 역할은 벡터를 변환해서 다른 곳으로 이동시킨다

numpy -ndarray 선형대수 데이터구조 https://datascienceschool.net/view-notebook/cd600e9627cd4f16bc4f6078231ab28c/

 scalar : -우리가 흔히 쓰는 1,2,3 이런것들

 vector : -벡터는 스칼라들의 모임 : n개의 스칼라가 모인 벡터를 n 차원 vector 라 함

 matrix :-행렬(matrix)은 스칼라들이 두 방향으로 뻗어나간 형태 
        : 세로로 m개, 가로로 n 개 (m by n matrix)
          n개의 행벡터와 m개의 열벡터
     
 tenser : - 3차원 ; 텐서는 같은 크기의 행렬이 여러 개 같이 묶여 있는 것
    컬러 이미지는 2차원의 행렬처럼 보이지만 
    사실 빨강, 초록, 파랑의 밝기를 나타내는 3가지의 이미지가 겹친 것
    

# 선형대수 

In [153]:
 선형대수 : 데이터 분석에 필요한 각종 계산을 돕는 학문
        선형대수를 사용하면 대량의 데이터를 포함하는 복잡한 계산과정을 간단한 수식으로 서술
        
        파이썬에서는 선형대수는 넘파이 패키지
        시각화로는 맷플롯립 패키지 사용
 

        선형으로 해결 => 비선형도 잘게 나누면 선형

        - 원점에서 나가는 모든 선. 그 선들의 각은 내적으로 구한다
        - 차원 추가 / 축소
        - 사이각 - 내적으로 구하기 ( cos 사이각. 유사도 )
        우리는 수업에 cos으로 theta 계산을 하기 때문에 내적
        
                                    - 외적 : vector - 방향값
                                    - 내적 : scalar


           
    
  
상관분석: 확률론과 통계학에서 두변수간에 어떤 선형적 또는 비선형적 관계를 갖는지 분석하는 방법
    두 변수는 서로 독립적인 관계이거나 상관된 관계일수 있다
    
    # 선형대수학 벡터의 내적을 이용한 대칭행렬 이해 
    # https://m.blog.naver.com/PostView.nhn?blogId=skkong89&logNo=221646308065&proxyReferer=https%3A%2F%2Fwww.google.com%2F

    상관계수 : -1 ~ 1 사이의 값으로 공분산을 평준화 한 값

        공분산( 음의 값 존재 ): 대칭을 중심으로 상관분산에서 상관계수도 2개
            공분산 : (x-xbar)(y-ybar) 를 표준화하면 상관계수 (-1 ~1)

# 고유벡터 : 새롭게 만들어진 축(직교하는 축) 을 가지고 원래 있던 축과 비교.



            
https://eda-ai-lab.tistory.com/383 내적/외적 참고

SyntaxError: invalid syntax (<ipython-input-153-e462ecda2d40>, line 1)

# vector & matrix ( 공간)

In [154]:
vector - 길이와 방향을 같는다
        벡터의 길이는 원점으로부터의 거리 방향을 같기 때문에 벡터끼리의 연산 cos사인 이용
        : 대각선 - 크기 (scaling) 한쪽방향으로의 선의 길이 
            벡터 a=[a1]  벡터 b=[b1]
                   [a2]         [b2]
                   [a3]         [b2]

                    
            벡터는 마치 행렬처럼 =>  ( n x 1 )열 => 열벡터로 간주 할수 있음.
            
            #https://angeloyeo.github.io/2019/08/20/correlation_and_inner_product.html
                    


SyntaxError: invalid syntax (<ipython-input-154-fa58f9acca99>, line 4)

In [157]:
ndarray = numpy 에서는 기본적으로 matrix 구조

세로로 m개, 가로로 n개 모인 ( m x n) 행렬

컴퓨터에 데이터를 입력시킬때 대개의 경우 -> 데이터는 이런 행렬 형태로 처리된다
뇌영상의 경우 PET fMRI 등은 3차원영상으로 이때 3차원 영상을 일렬로 쭈욱 펴서 1차원 벡터라이즈 함.
(2차원 이미지 가장작은단위 픽셀pixel, 3차원 이미지에서는 가장작은단위 복셀voxel)

#https://sites.google.com/site/hkleebrain/home/-site-hkleebrain-home-presentation/vector-matrix-and-their-operations

SyntaxError: invalid syntax (<ipython-input-157-7b23b52d0787>, line 1)

# 행렬을 나눗셈할때 => 역행렬을 구해서 곱한다

In [ ]:
       A x       = b
(n x n ) (n x 1) = n x 1

A 는  행렬(매트릭스) x 와 y n콜룸을 가진 벡터.

 A^-1A=I가 되는 행렬
    숫자 1처럼 곱했을 때 AI=A, IA=A와 같이 자기자신이 되게 하는 행렬
    역행렬=> I를 identity matrix
        
   Ax = b → 양쪽에 역행렬 곱하면 ( A^-1Ax = A^-1b ) 
                                 → ( I* x = A^-1b )→ x = A^-1b

    
    행렬은 나눗셈이 없어서 역행렬 곱해야 한다

# Matrix 행렬의 종류

# 수학적으로 참고할것

In [2]:

- 정방행렬 : 정사각형(행과 열수가 같은 행렬)
- 대칭행렬 : 우상단과 좌하단이 같은 것
           : 모든 상관분석을 하기 위해 행과 열의 같은 변수를 준다. 
            
- 대각행렬 : scale을 변화시키는 요소 (대각행렬이 전부 1이면 다른거랑곱했을때 자신이 나옴)
- 단위행렬(identity) : 행렬곱의 항등원, 행렬과 역행렬을 곱하면 단위행렬

- 역행렬 : 행렬의 나눗셈을 구해서 곱해지는 행렬( 정방행렬만 가능 )
- 특이행렬 : 역행렬이 없는 행렬
    
- 직교행렬 : 축의 정직교
           : 각 축간의 내적이 0 인 행렬
            
-  행렬 분해 :행렬을 특정한 구조를 가지니 다른 행렬의 곱으로 나타내는 것
    - 3x3 행렬은 3x1 크기의 두행렬과 1x1 크기의 대각 행렬을 통해 나타낼수 있다.
    -선형 방정식의 해를 구하거나, 행렬 계산을 효율적으로 하거나, 행렬의 특정구조를 밝히는 목적
    -역행렬을 구하기 위해서


      
            
- 정방행렬이면서 대칭행렬 : 공분산행렬, 상관계수 행렬, 거리행렬
    
    
- 공분산 : 두 수간의 관계 ((한수 - 평균) * (다른수 - 평균)) / (n-1)
     2개의 확률변수의 상관정도를 나타내는 값
        만약 2개의 변수중 하나의 값이 상승하는 경향을 보일 때, 
        다른 값도 상승하는 경향의 상관관계에 있다면, 
        공분산의 값은 양수가 될 것이다. 
        반대로 2개의 변수중 하나의 값이 상승하는 경향을 보일 때, 
        다른 값이 하강하는 경향을 보인다면 공분산의 값은 음수가 된다. 

        
- 상관계수(표준화 -1 ~1) : 공분산 / 표준편차의 곱

SyntaxError: invalid syntax (<ipython-input-2-bd9e66828dc1>, line 1)

In [ ]:
내적 = 특징추출 => @  행렬간의 곲셈 : 두가지 변수가 하나의변수 = > 차원축소
            많은 변수들 사이에서 사잇각을 구해서 
            같은 특징을 합쳐서 
            
            소수로 분류한다 =>       매트릭스는 분류 & 예측........?
        
        

In [ ]:
 벡터 = > 매트릭스 : 공간을 변환하는것 
        
        회전매트릭스 * 이동 매트릭스 : 변환의 합




Translation = >이동매트릭스 * 회전 매트릭스 MRS : move rotate scale
        
원본 벡터 위에 다른 벡터를 더하여 다른 위치의 새로운 벡터를 반환하는 작업입니다.
따라서 벡터를 moving(이동)시킵니다. 

-Rotation(회전)
마지막 변환은 비교적 이해하기 쉽고 2D, 3D 공간에서 시각화하기 쉽지만 회전은 좀 까다롭습니다.
 
    Homogeneous coordinates(동차 좌표)
벡터의 w 요소는 homogeneous coordinate(동차 좌표)라고도 불립니다. 
동차 좌표로부터 3D 벡터를 가져오기 위해 x, y, z 좌표를 w 좌표로 나눕니다. 
우리는 일반적으로 w 요소가 대부분 1.0이기 때문에 알아차리지 않습니다. 
동차 좌표를 사용하면 여러가지 장점이 있습니다. 3D 벡터를 이동시킬 수 있도록 하고
(w 요소 없이는 벡터를 이동시키지 못합니다) 
3D 비주얼을 생성하기 위해 다음 강좌에서 사용할 것입니다.

  또한 동차 좌표가 0일 경우 벡터는 특병히 방향 벡터라고 불립니다. 
    w 좌표의 값이 0인 좌표는 이동시킬 수 없기 때문입니다.       
    
    
    
https://heinleinsgame.tistory.com/10
        